#!/bin/zsh

# X

# Keyboard
setxkbmap gb
setxkbmap -option compose:menu
setxkbmap -option terminate:ctrl_alt_bksp
xmodmap -e "clear Mod4"

# Resources
xsetroot -cursor_name left_ptr
xrdb -load ~/projects/home/config/xorg/Xdefaults

# /X

# APPS

urxvtd -q -f -o
randombg &

if ! pgrep -fl "emacs --daemon" &>/dev/null; then
    emacs --daemon
fi

# /APPS

# WM

if [[ "$WM" != "" ]]; then
    urxvt &
    exec $WM
elif [[ -e /tmp/notile ]]; then
    urxvt &
    exec openbox
else
    exec stumpwm
fi

# /WM
