#!/bin/zsh

# X

setxkbmap -option terminate:ctrl_alt_bksp
xrdb -load ~/projects/home/config/xorg/Xdefaults
xsetroot -cursor_name left_ptr
# /X

# APPS

urxvtd -q -f -o

randombg

# /APPS

# WM

if [[ "$WM" != "" ]]; then
    urxvt &
    exec $WM
else
    exec xmonad
fi

# /WM
