#!/bin/zsh

# X

setxkbmap -option terminate:ctrl_alt_bksp
xsetroot -d :1.0 -cursor_name left_ptr
xsetroot -d :1.1 -cursor_name left_ptr
xrdb -load ~/projects/home/config/xorg/Xdefaults

# /X

# APPS

urxvtd -q -f -o

DISPLAY=:1.0 randombg /usr/share/wallpapers/rotation/landscape &
DISPLAY=:1.1 randombg /usr/share/wallpapers/rotation/portrait  &

# /APPS

# WM

if [[ "$WM" != "" ]]; then
    urxvt &
    exec $WM
elif [[ -e /tmp/notile ]]; then
    urxvt &
    exec openbox
else
    exec stumpwm
fi

# /WM
