name = "Martin Roboscan 812"

# dmx = {"command" : {"argument" : [start of range, channel offset, description], ...}, ...}

dmx = {"control"  : {"no"     : [0,   0, "No strobe"],
                     "gobo"   : [11,  0, "Gobo strobe"],
                     "colour" : [75,  0, "Colour strobe"],
                     "auto"   : [139, 0, "Remote auto trig"],
                     "music"  : [171, 0, "Remote music trig"],
                     "reset"  : [203, 0, "Reset fixture"],
                     "lamp"   : [236, 0, "Lamp power on"]},
       
       "colour" : {"b-w"   : [0,   1, "Black to white"],
                   "w-1"   : [15,  1, "White to purple"],
                   "1-2"   : [30,  1, "Purple to peach"],
                   "2-3"   : [45,  1, "Peach to red"],
                   "3-4"   : [60,  1, "Red to orange"],
                   "4-5"   : [75,  1, "Orange to light orange"],
                   "5-6"   : [90,  1, "Light orange to yellow"],
                   "6-7"   : [105, 1, "Yellow to green"],
                   "7-8"   : [120, 1, "Green to dark green"],
                   "8-9"   : [135, 1, "Dark green to blue"],
                   "9-10"  : [150, 1, "Blue to dark blue"],
                   "10-11" : [165, 1, "Dark blue to white"],
                   "11"    : [180, 1, "White"],
                   "10"    : [185, 1, "Dark Blue"],
                   "9"     : [190, 1, "Blue"],
                   "8"     : [195, 1, "Dark Green"],
                   "7"     : [200, 1, "Green"],
                   "6"     : [205, 1, "Yellow"],
                   "5"     : [210, 1, "Light Orange"],
                   "4"     : [215, 1, "Orange"],
                   "3"     : [220, 1, "Red"],
                   "2"     : [225, 1, "Peach"],
                   "1"     : [230, 1, "Purple"],
                   "w"     : [235, 1, "White"],
                   "b"     : [240, 1, "Black"]},

       "gobo"   : {"c-o"   : [0,   2, "Closed to open"],
                   "o-1"   : [15,  2, "Open to circle"],
                   "1-2"   : [30,  2, "Circle to bar"],
                   "2-3"   : [45,  2, "Bar to curved triangle"],
                   "3-4"   : [60 , 2, "Curved triangle to patterned circle"],
                   "4-5"   : [75,  2, "Patterened circle to star"],
                   "5-6"   : [90,  2, "Star to bubbles"],
                   "6-7"   : [105, 2, "Bubbles to pentagons"],
                   "7-8"   : [120, 2, "Pentagons to ring"],
                   "8-9"   : [135, 2, "Ring to circle ring"],
                   "9-10"  : [150, 2, "Circle ring to squares"],
                   "10-11" : [165, 2, "Squares to triangle"],
                   "11"    : [180, 2, "Triangle"],
                   "10"    : [185, 2, "Squares"],
                   "9"     : [190, 2, "Circle ring"],
                   "8"     : [195, 2, "Ring"],
                   "7"     : [200, 2, "Pentagons"],
                   "6"     : [205, 2, "Bubbles"],
                   "5"     : [210, 2, "Star"],
                   "4"     : [215, 2, "Patterned circle"],
                   "3"     : [220, 2, "Curved triangle"],
                   "2"     : [225, 2, "Bar"],
                   "1"     : [230, 2, "Circle"],
                   "o"     : [235, 2, "Open"],
                   "c"     : [240, 2, "Closed"]},

       "move"   : {"pan"  : [0, 3, "Pan"],
                   "tilt" : [0, 4, "Tilt"]},
       
       "speed"  : {"move" : [0, 5, "Movement speed"],
                   "col" :  [0, 6, "Colour/gobo speed"]}}

channels = ["Control", "Colour","Gobo", "Pan", "Tilt", "Move Speed", "Col. Speed"]

defaults = [0, 0, 0, 127, 127, 0, 0]
