#!/bin/bash

target=""
linkname=""

while [[ "$target" == "" ]] || [[ "$linkname" == "" ]]; do
    if [[ ! "$1" == -* ]]; then
        if [[ "$target" == "" ]]; then
            target="$1"
        elif [[ "$linkname" == "" ]]; then
            linkname="$1"
        fi
    fi
    shift
done

[[ ! "$target"   == /* ]] && target=`pwd`/$target
[[ ! "$linkname" == /* ]] && linkname=`pwd`/$linkname

if [[ ! -e "$linkname" ]]; then
    [[ ! -e "$(dirname "$linkname")" ]] && mkdir -p $(dirname "$linkname")
    touch "$linkname"
fi

settrans -a "$linkname" /hurd/firmlink "$target"
