#!/bin/bash

# Get a writable / running so boot can continue as normal
echo "Making filesystem writable... "

# ramdisk
/bin/settrans -a /dev/time /hurd/storeio --no-cache time
/bin/settrans -a /servers/socket/1 /hurd/pflocal
/bin/settrans -a /dev/ramdisk /hurd/storeio -Tcopy /boot/ramdisk.ext2fs
/bin/settrans -a /boot/tmpfs /hurd/ext2fs.static /dev/ramdisk

# unionfs
mkdir /boot/tmpfs/{newroot,writable}

while read dir; do
    mkdir "$dir"
done < /libexec/dirs

/bin/settrans -a /boot/tmpfs/newroot /hurd/unionfs / /boot/tmpfs/writable -w
/bin/cp /libexec/newln /boot/tmpfs/writable/bin/ln
chmod +x /boot/tmpfs/writable/bin/ln

# chroot
/bin/chroot /boot/tmpfs/newroot /libexec/runsystem_stage2
halt