(defun times-table (table start end)
  (dotimes (i (+ end 1))
	(if (> (+ i 1) start)
		(format t "~d " (* table i))))
  (format t "~%"))

(defun times-tables (start end lim1 lim2)
  (dotimes (i (+ end 1))
	(if (> (+ i 1) start)
		(times-table i lim1 lim2))))