#!/bin/zsh

cmdline="`cat /proc/cmdline`"

function notinschool()
{
    grep -q school /proc/cmdline
}

function inschool()
{
    grep -q school /proc/cmdline
    return $[1 - $?]
}

if [[ -f /var/run/daemons/hal ]]; then
    # X
        # Keyboard
        setxkbmap gb
        setxkbmap -option compose:menu
        setxkbmap -option terminate:ctrl_alt_bksp
        xmodmap -e "clear Mod4"

        # Touchpad
        synclient MinSpeed=0.10
        synclient MaxSpeed=0.80
        synclient AccelFactor=0.50
        synclient VertEdgeScroll=1
        synclient HorizEdgeScroll=1

        # Other
        xsetroot -cursor_name left_ptr
        xrdb -load ~/.Xdefaults
    # /X

    # BCompA
    inschool    && bcompa login true &>~/.data/bcompa &
    notinschool && bcompa login      &>~/.data/bcompa &
    
    # Window Manager
    exec stumpwm
fi
