#!/bin/zsh

# X

# Keyboard
setxkbmap gb
setxkbmap -option compose:menu
setxkbmap -option terminate:ctrl_alt_bksp
xmodmap -e "clear Mod4"

# Touchpad
synclient MinSpeed=0.10
synclient MaxSpeed=0.80
synclient AccelFactor=0.50
synclient VertEdgeScroll=1
synclient HorizEdgeScroll=1

# Other
xsetroot -cursor_name left_ptr
xrdb -load ~/.Xdefaults

# /X

# APPS

if grep -q school /proc/cmdline; then
    urxvtc -e emacs &>/dev/null &
else
    # Network
    ping google.com -c1 || sudo netcfg-auto-wireless
    ping eihort     -c1 || sudo eihort up
    
    # Programs
    mpddp
    ucron      &>/dev/null &
    opera      &>/dev/null &
    claws-mail &>/dev/null &
fi

randombg

# /APPS

# WM

if [[ "$WM" != "" ]]; then
    exec $WM
else
    exec stumpwm
fi

# /WM