#!/usr/bin/env bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload

# remove all existing keybindings
hc keyunbind --all

# keybindings
Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close

# Spawning programs
hc keybind $Mod-x       spawn gmrun
hc keybind XF86HomePage spawn chromium --enable-ipv6 --force-device-scale-factor
hc keybind XF86Mail     spawn claws-mail
hc keybind Print        spawn scrot ~/tmp/screenshot.png

if type urxvtc &>/dev/null; then
  hc keybind $Mod-Return    spawn urxvtc
  hc keybind $Mod-backslash spawn urxvtc -e newtmux
elif type xfce4-terminal &>/dev/null; then
  hc keybind $Mod-Return    spawn xfce4-terminal
  hc keybind $Mod-backslash spawn xfce4-terminal -e newtmux
else
  hc keybind $Mod-Return    spawn xterm
  hc keybind $Mod-backslash spawn xterm -e newtmux
fi
if type dm-tool &>/dev/null; then
  hc keybind XF86Sleep spawn dm-tool lock
elif type slock &>/dev/null; then
  hc keybind XF86Sleep spawn slock
elif type xscreensaver-command &>/dev/null; then
  hc keybind XF86Sleep spawn xscreensaver-command -lock
fi

# Media keys
hc keybind XF86AudioPlay        spawn mpc toggle
hc keybind XF86AudioStop        spawn mpc stop
hc keybind XF86AudioPrev        spawn mpc prev
hc keybind XF86AudioNext        spawn mpc next
hc keybind XF86AudioMute        spawn amixer set Master toggle
hc keybind XF86AudioLowerVolume spawn amixer set Master 1%-
hc keybind XF86AudioRaiseVolume spawn amixer set Master 1%+

# Displays
hc keybind $Mod-Control-Shift-l spawn xrandr_rotate landscape landscape
hc keybind $Mod-Control-l       spawn xrandr_rotate landscape portrait
hc keybind $Mod-Control-p       spawn xrandr_rotate portrait  landscape
hc keybind $Mod-Control-Shift-p spawn xrandr_rotate portrait  portrait

# basic movement
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right

# moving clients
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-space cycle_layout 1
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize
hc set mouse_recenter_gap 0

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent
hc set focus_follows_mouse 1

# theme
source ~/.config/herbstluftwm/theme.sh

# rules
hc unrule -F
hc rule focus=off
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule class=Gmrun pseudotile=on focus=on

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# detect monitors
hc detect_monitors
