#!/bin/zsh

# X

# Keyboard
setxkbmap gb
setxkbmap -option compose:menu
setxkbmap -option terminate:ctrl_alt_bksp
xmodmap -e "clear Mod4"

# Screensaver
xset s noblank
xset s off

# Other
xsetroot -cursor_name left_ptr
xrdb -load ~/.config/xorg/Xdefaults

# /X

# APPS

urxvtd -q -f -o
ucron &>/dev/null &
randombg

# /APPS

# WM

if [[ "$WM" != "" ]]; then
    exec $WM
else
    exec stumpwm
fi

# /WM