#!/bin/zsh

# X

# Keyboard
setxkbmap gb
setxkbmap -option compose:menu
setxkbmap -option terminate:ctrl_alt_bksp
xmodmap -e "clear Mod4"

# Touchpad
synclient MinSpeed=0.10
synclient MaxSpeed=0.80
synclient AccelFactor=0.50
synclient VertEdgeScroll=1
synclient HorizEdgeScroll=1

# Screensaver
xset s noblank
xset s off

# Other
xsetroot -cursor_name left_ptr
xrdb -load ~/.config/xorg/Xdefaults

# /X

# APPS

urxvtd -q -f -o
ucron &>/dev/null &

if grep -q school /proc/cmdline; then
    feh --bg-scale "/usr/share/wallpapers/Linux/Archstone Blue.png"
else
    randombg
fi

# /APPS

# WM

if [[ "$WM" != "" ]]; then
    exec $WM
else
    exec stumpwm
fi

# /WM